// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'subtitle.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Subtitle _$SubtitleFromJson(Map<String, dynamic> json) => Subtitle(
      url: json['url'] as String?,
      mimeType: json['mimeType'] as String?,
      name: json['name'] as String?,
      code: json['code'] as String?,
      autoGenerated: json['autoGenerated'] as bool?,
    );

Map<String, dynamic> _$SubtitleToJson(Subtitle instance) => <String, dynamic>{
      'url': instance.url,
      'mimeType': instance.mimeType,
      'name': instance.name,
      'code': instance.code,
      'autoGenerated': instance.autoGenerated,
    };
