import 'package:json_annotation/json_annotation.dart';

part 'subtitle.g.dart';

@JsonSerializable()
class Subtitle {
  String? url;
  String? mimeType;
  String? name;
  String? code;
  bool? autoGenerated;

  Subtitle({
    this.url,
    this.mimeType,
    this.name,
    this.code,
    this.autoGenerated,
  });

  factory Subtitle.fromJson(Map<String, dynamic> json) {
    return _$SubtitleFromJson(json);
  }

  Map<String, dynamic> toJson() => _$SubtitleToJson(this);
}
