import 'package:json_annotation/json_annotation.dart';
import 'video_thumbnail.dart';

part 'invidious_search_resp.g.dart';

//--------MAIN INVIDIOUS SEARCH RESPOSE MODEL--------//
// `flutter pub run build_runner build` to generate file

@JsonSerializable()
class InvidiousSearchResp {
  String? type;
  String? title;
  String? videoId;
  String? author;
  String? authorId;
  String? authorUrl;
  bool? authorVerified;
  List<VideoThumbnail>? videoThumbnails;
  String? description;
  String? descriptionHtml;
  int? viewCount;
  String? viewCountText;
  int? published;
  String? publishedText;
  int? lengthSeconds;
  bool? liveNow;
  bool? premium;
  bool? isUpcoming;

  // Fields specific to playlists
  String? playlistId;
  String? playlistThumbnail;
  int? videoCount;
  List<PlaylistVideo>? videos;

  // Fields specific to channels
  List<ChannelThumbnail>? authorThumbnails;
  bool? autoGenerated;
  int? subCount;
  int? channelVideoCount;
  String? channelHandle;

  InvidiousSearchResp({
    this.type,
    this.title,
    this.videoId,
    this.author,
    this.authorId,
    this.authorUrl,
    this.authorVerified,
    this.videoThumbnails,
    this.description,
    this.descriptionHtml,
    this.viewCount,
    this.viewCountText,
    this.published,
    this.publishedText,
    this.lengthSeconds,
    this.liveNow,
    this.premium,
    this.isUpcoming,
    this.playlistId,
    this.playlistThumbnail,
    this.videoCount,
    this.videos,
    this.authorThumbnails,
    this.autoGenerated,
    this.subCount,
    this.channelVideoCount,
    this.channelHandle,
  });

  factory InvidiousSearchResp.fromJson(Map<String, dynamic> json) {
    return _$InvidiousSearchRespFromJson(json);
  }

  Map<String, dynamic> toJson() => _$InvidiousSearchRespToJson(this);
}

@JsonSerializable()
class PlaylistVideo {
  String? title;
  String? videoId;
  int? lengthSeconds;
  List<VideoThumbnail>? videoThumbnails;

  PlaylistVideo({
    this.title,
    this.videoId,
    this.lengthSeconds,
    this.videoThumbnails,
  });

  factory PlaylistVideo.fromJson(Map<String, dynamic> json) {
    return _$PlaylistVideoFromJson(json);
  }

  Map<String, dynamic> toJson() => _$PlaylistVideoToJson(this);
}

@JsonSerializable()
class ChannelThumbnail {
  String? url;
  int? width;
  int? height;

  ChannelThumbnail({
    this.url,
    this.width,
    this.height,
  });

  factory ChannelThumbnail.fromJson(Map<String, dynamic> json) {
    return _$ChannelThumbnailFromJson(json);
  }

  Map<String, dynamic> toJson() => _$ChannelThumbnailToJson(this);
}
