// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'invidious_search_resp.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

InvidiousSearchResp _$InvidiousSearchRespFromJson(Map<String, dynamic> json) =>
    InvidiousSearchResp(
      type: json['type'] as String?,
      title: json['title'] as String?,
      videoId: json['videoId'] as String?,
      author: json['author'] as String?,
      authorId: json['authorId'] as String?,
      authorUrl: json['authorUrl'] as String?,
      authorVerified: json['authorVerified'] as bool?,
      videoThumbnails: (json['videoThumbnails'] as List<dynamic>?)
          ?.map((e) => VideoThumbnail.fromJson(e as Map<String, dynamic>))
          .toList(),
      description: json['description'] as String?,
      descriptionHtml: json['descriptionHtml'] as String?,
      viewCount: (json['viewCount'] as num?)?.toInt(),
      viewCountText: json['viewCountText'] as String?,
      published: (json['published'] as num?)?.toInt(),
      publishedText: json['publishedText'] as String?,
      lengthSeconds: (json['lengthSeconds'] as num?)?.toInt(),
      liveNow: json['liveNow'] as bool?,
      premium: json['premium'] as bool?,
      isUpcoming: json['isUpcoming'] as bool?,
      playlistId: json['playlistId'] as String?,
      playlistThumbnail: json['playlistThumbnail'] as String?,
      videoCount: (json['videoCount'] as num?)?.toInt(),
      videos: (json['videos'] as List<dynamic>?)
          ?.map((e) => PlaylistVideo.fromJson(e as Map<String, dynamic>))
          .toList(),
      authorThumbnails: (json['authorThumbnails'] as List<dynamic>?)
          ?.map((e) => ChannelThumbnail.fromJson(e as Map<String, dynamic>))
          .toList(),
      autoGenerated: json['autoGenerated'] as bool?,
      subCount: (json['subCount'] as num?)?.toInt(),
      channelVideoCount: (json['channelVideoCount'] as num?)?.toInt(),
      channelHandle: json['channelHandle'] as String?,
    );

Map<String, dynamic> _$InvidiousSearchRespToJson(
        InvidiousSearchResp instance) =>
    <String, dynamic>{
      'type': instance.type,
      'title': instance.title,
      'videoId': instance.videoId,
      'author': instance.author,
      'authorId': instance.authorId,
      'authorUrl': instance.authorUrl,
      'authorVerified': instance.authorVerified,
      'videoThumbnails': instance.videoThumbnails,
      'description': instance.description,
      'descriptionHtml': instance.descriptionHtml,
      'viewCount': instance.viewCount,
      'viewCountText': instance.viewCountText,
      'published': instance.published,
      'publishedText': instance.publishedText,
      'lengthSeconds': instance.lengthSeconds,
      'liveNow': instance.liveNow,
      'premium': instance.premium,
      'isUpcoming': instance.isUpcoming,
      'playlistId': instance.playlistId,
      'playlistThumbnail': instance.playlistThumbnail,
      'videoCount': instance.videoCount,
      'videos': instance.videos,
      'authorThumbnails': instance.authorThumbnails,
      'autoGenerated': instance.autoGenerated,
      'subCount': instance.subCount,
      'channelVideoCount': instance.channelVideoCount,
      'channelHandle': instance.channelHandle,
    };

PlaylistVideo _$PlaylistVideoFromJson(Map<String, dynamic> json) =>
    PlaylistVideo(
      title: json['title'] as String?,
      videoId: json['videoId'] as String?,
      lengthSeconds: (json['lengthSeconds'] as num?)?.toInt(),
      videoThumbnails: (json['videoThumbnails'] as List<dynamic>?)
          ?.map((e) => VideoThumbnail.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$PlaylistVideoToJson(PlaylistVideo instance) =>
    <String, dynamic>{
      'title': instance.title,
      'videoId': instance.videoId,
      'lengthSeconds': instance.lengthSeconds,
      'videoThumbnails': instance.videoThumbnails,
    };

ChannelThumbnail _$ChannelThumbnailFromJson(Map<String, dynamic> json) =>
    ChannelThumbnail(
      url: json['url'] as String?,
      width: (json['width'] as num?)?.toInt(),
      height: (json['height'] as num?)?.toInt(),
    );

Map<String, dynamic> _$ChannelThumbnailToJson(ChannelThumbnail instance) =>
    <String, dynamic>{
      'url': instance.url,
      'width': instance.width,
      'height': instance.height,
    };
