import 'package:fluxtube/core/model/region_model.dart';

final List<RegionModel> regions = [
  RegionModel(name: 'Afghanistan', code: 'AF'),
  RegionModel(name: 'Albania', code: 'AL'),
  RegionModel(name: 'Algeria', code: 'DZ'),
  RegionModel(name: 'Andorra', code: 'AD'),
  RegionModel(name: 'Angola', code: 'AO'),
  RegionModel(name: 'Antigua and Barbuda', code: 'AG'),
  RegionModel(name: 'Argentina', code: 'AR'),
  RegionModel(name: 'Armenia', code: 'AM'),
  RegionModel(name: 'Australia', code: 'AU'),
  RegionModel(name: 'Austria', code: 'AT'),
  RegionModel(name: 'Azerbaijan', code: 'AZ'),
  RegionModel(name: 'Bahamas', code: 'BS'),
  RegionModel(name: 'Bahrain', code: 'BH'),
  RegionModel(name: 'Bangladesh', code: 'BD'),
  RegionModel(name: 'Barbados', code: 'BB'),
  RegionModel(name: 'Belarus', code: 'BY'),
  RegionModel(name: 'Belgium', code: 'BE'),
  RegionModel(name: 'Belize', code: 'BZ'),
  RegionModel(name: 'Benin', code: 'BJ'),
  RegionModel(name: 'Bhutan', code: 'BT'),
  RegionModel(name: 'Bolivia (Plurinational State of)', code: 'BO'),
  RegionModel(name: 'Bosnia and Herzegovina', code: 'BA'),
  RegionModel(name: 'Botswana', code: 'BW'),
  RegionModel(name: 'Brazil', code: 'BR'),
  RegionModel(name: 'Brunei Darussalam', code: 'BN'),
  RegionModel(name: 'Bulgaria', code: 'BG'),
  RegionModel(name: 'Burkina Faso', code: 'BF'),
  RegionModel(name: 'Burundi', code: 'BI'),
  RegionModel(name: 'Cabo Verde', code: 'CV'),
  RegionModel(name: 'Cambodia', code: 'KH'),
  RegionModel(name: 'Cameroon', code: 'CM'),
  RegionModel(name: 'Canada', code: 'CA'),
  RegionModel(name: 'Central African Republic', code: 'CF'),
  RegionModel(name: 'Chad', code: 'TD'),
  RegionModel(name: 'Chile', code: 'CL'),
  RegionModel(name: 'China', code: 'CN'),
  RegionModel(name: 'Colombia', code: 'CO'),
  RegionModel(name: 'Comoros', code: 'KM'),
  RegionModel(name: 'Congo', code: 'CG'),
  RegionModel(name: 'Congo, Democratic Republic of the', code: 'CD'),
  RegionModel(name: 'Costa Rica', code: 'CR'),
  RegionModel(name: "Côte d'Ivoire", code: 'CI'),
  RegionModel(name: 'Croatia', code: 'HR'),
  RegionModel(name: 'Cuba', code: 'CU'),
  RegionModel(name: 'Cyprus', code: 'CY'),
  RegionModel(name: 'Czechia', code: 'CZ'),
  RegionModel(name: 'Denmark', code: 'DK'),
  RegionModel(name: 'Djibouti', code: 'DJ'),
  RegionModel(name: 'Dominica', code: 'DM'),
  RegionModel(name: 'Dominican Republic', code: 'DO'),
  RegionModel(name: 'Ecuador', code: 'EC'),
  RegionModel(name: 'Egypt', code: 'EG'),
  RegionModel(name: 'El Salvador', code: 'SV'),
  RegionModel(name: 'Equatorial Guinea', code: 'GQ'),
  RegionModel(name: 'Eritrea', code: 'ER'),
  RegionModel(name: 'Estonia', code: 'EE'),
  RegionModel(name: 'Eswatini', code: 'SZ'),
  RegionModel(name: 'Ethiopia', code: 'ET'),
  RegionModel(name: 'Fiji', code: 'FJ'),
  RegionModel(name: 'Finland', code: 'FI'),
  RegionModel(name: 'France', code: 'FR'),
  RegionModel(name: 'Gabon', code: 'GA'),
  RegionModel(name: 'Gambia', code: 'GM'),
  RegionModel(name: 'Georgia', code: 'GE'),
  RegionModel(name: 'Germany', code: 'DE'),
  RegionModel(name: 'Ghana', code: 'GH'),
  RegionModel(name: 'Greece', code: 'GR'),
  RegionModel(name: 'Grenada', code: 'GD'),
  RegionModel(name: 'Guatemala', code: 'GT'),
  RegionModel(name: 'Guinea', code: 'GN'),
  RegionModel(name: 'Guinea-Bissau', code: 'GW'),
  RegionModel(name: 'Guyana', code: 'GY'),
  RegionModel(name: 'Haiti', code: 'HT'),
  RegionModel(name: 'Honduras', code: 'HN'),
  RegionModel(name: 'Hong Kong', code: 'HK'),
  RegionModel(name: 'Hungary', code: 'HU'),
  RegionModel(name: 'Iceland', code: 'IS'),
  RegionModel(name: 'India', code: 'IN'),
  RegionModel(name: 'Indonesia', code: 'ID'),
  RegionModel(name: 'Iran (Islamic Republic of)', code: 'IR'),
  RegionModel(name: 'Iraq', code: 'IQ'),
  RegionModel(name: 'Ireland', code: 'IE'),
  RegionModel(name: 'Israel', code: 'IL'),
  RegionModel(name: 'Italy', code: 'IT'),
  RegionModel(name: 'Jamaica', code: 'JM'),
  RegionModel(name: 'Japan', code: 'JP'),
  RegionModel(name: 'Jordan', code: 'JO'),
  RegionModel(name: 'Kazakhstan', code: 'KZ'),
  RegionModel(name: 'Kenya', code: 'KE'),
  RegionModel(name: 'Kiribati', code: 'KI'),
  RegionModel(name: "Korea (Democratic People's Republic of)", code: 'KP'),
  RegionModel(name: 'Korea, Republic of', code: 'KR'),
  RegionModel(name: 'Kuwait', code: 'KW'),
  RegionModel(name: 'Kyrgyzstan', code: 'KG'),
  RegionModel(name: "Lao People's Democratic Republic", code: 'LA'),
  RegionModel(name: 'Latvia', code: 'LV'),
  RegionModel(name: 'Lebanon', code: 'LB'),
  RegionModel(name: 'Lesotho', code: 'LS'),
  RegionModel(name: 'Liberia', code: 'LR'),
  RegionModel(name: 'Libya', code: 'LY'),
  RegionModel(name: 'Liechtenstein', code: 'LI'),
  RegionModel(name: 'Lithuania', code: 'LT'),
  RegionModel(name: 'Luxembourg', code: 'LU'),
  RegionModel(name: 'Madagascar', code: 'MG'),
  RegionModel(name: 'Malawi', code: 'MW'),
  RegionModel(name: 'Malaysia', code: 'MY'),
  RegionModel(name: 'Maldives', code: 'MV'),
  RegionModel(name: 'Mali', code: 'ML'),
  RegionModel(name: 'Malta', code: 'MT'),
  RegionModel(name: 'Marshall Islands', code: 'MH'),
  RegionModel(name: 'Mauritania', code: 'MR'),
  RegionModel(name: 'Mauritius', code: 'MU'),
  RegionModel(name: 'Mexico', code: 'MX'),
  RegionModel(name: 'Micronesia (Federated States of)', code: 'FM'),
  RegionModel(name: 'Moldova, Republic of', code: 'MD'),
  RegionModel(name: 'Monaco', code: 'MC'),
  RegionModel(name: 'Mongolia', code: 'MN'),
  RegionModel(name: 'Montenegro', code: 'ME'),
  RegionModel(name: 'Morocco', code: 'MA'),
  RegionModel(name: 'Mozambique', code: 'MZ'),
  RegionModel(name: 'Myanmar', code: 'MM'),
  RegionModel(name: 'Namibia', code: 'NA'),
  RegionModel(name: 'Nauru', code: 'NR'),
  RegionModel(name: 'Nepal', code: 'NP'),
  RegionModel(name: 'Netherlands', code: 'NL'),
  RegionModel(name: 'New Zealand', code: 'NZ'),
  RegionModel(name: 'Nicaragua', code: 'NI'),
  RegionModel(name: 'Niger', code: 'NE'),
  RegionModel(name: 'Nigeria', code: 'NG'),
  RegionModel(name: 'North Macedonia', code: 'MK'),
  RegionModel(name: 'Norway', code: 'NO'),
  RegionModel(name: 'Oman', code: 'OM'),
  RegionModel(name: 'Pakistan', code: 'PK'),
  RegionModel(name: 'Palau', code: 'PW'),
  RegionModel(name: 'Panama', code: 'PA'),
  RegionModel(name: 'Papua New Guinea', code: 'PG'),
  RegionModel(name: 'Paraguay', code: 'PY'),
  RegionModel(name: 'Peru', code: 'PE'),
  RegionModel(name: 'Philippines', code: 'PH'),
  RegionModel(name: 'Poland', code: 'PL'),
  RegionModel(name: 'Portugal', code: 'PT'),
  RegionModel(name: 'Qatar', code: 'QA'),
  RegionModel(name: 'Romania', code: 'RO'),
  RegionModel(name: 'Russian Federation', code: 'RU'),
  RegionModel(name: 'Rwanda', code: 'RW'),
  RegionModel(name: 'Saint Kitts and Nevis', code: 'KN'),
  RegionModel(name: 'Saint Lucia', code: 'LC'),
  RegionModel(name: 'Saint Vincent and the Grenadines', code: 'VC'),
  RegionModel(name: 'Samoa', code: 'WS'),
  RegionModel(name: 'San Marino', code: 'SM'),
  RegionModel(name: 'Sao Tome and Principe', code: 'ST'),
  RegionModel(name: 'Saudi Arabia', code: 'SA'),
  RegionModel(name: 'Senegal', code: 'SN'),
  RegionModel(name: 'Serbia', code: 'RS'),
  RegionModel(name: 'Seychelles', code: 'SC'),
  RegionModel(name: 'Sierra Leone', code: 'SL'),
  RegionModel(name: 'Singapore', code: 'SG'),
  RegionModel(name: 'Slovakia', code: 'SK'),
  RegionModel(name: 'Slovenia', code: 'SI'),
  RegionModel(name: 'Solomon Islands', code: 'SB'),
  RegionModel(name: 'Somalia', code: 'SO'),
  RegionModel(name: 'South Africa', code: 'ZA'),
  RegionModel(name: 'South Sudan', code: 'SS'),
  RegionModel(name: 'Spain', code: 'ES'),
  RegionModel(name: 'Sri Lanka', code: 'LK'),
  RegionModel(name: 'Sudan', code: 'SD'),
  RegionModel(name: 'Suriname', code: 'SR'),
  RegionModel(name: 'Sweden', code: 'SE'),
  RegionModel(name: 'Switzerland', code: 'CH'),
  RegionModel(name: 'Syrian Arab Republic', code: 'SY'),
  RegionModel(name: 'Tajikistan', code: 'TJ'),
  RegionModel(name: 'Thailand', code: 'TH'),
  RegionModel(name: 'Timor-Leste', code: 'TL'),
  RegionModel(name: 'Togo', code: 'TG'),
  RegionModel(name: 'Tonga', code: 'TO'),
  RegionModel(name: 'Trinidad and Tobago', code: 'TT'),
  RegionModel(name: 'Tunisia', code: 'TN'),
  RegionModel(name: 'Turkey', code: 'TR'),
  RegionModel(name: 'Turkmenistan', code: 'TM'),
  RegionModel(name: 'Tuvalu', code: 'TV'),
  RegionModel(name: 'Uganda', code: 'UG'),
  RegionModel(name: 'Ukraine', code: 'UA'),
  RegionModel(name: 'United Arab Emirates', code: 'AE'),
  RegionModel(name: 'United Kingdom of Great Britain and Northern Ireland', code: 'GB'),
  RegionModel(name: 'United Republic of Tanzania', code: 'TZ'),
  RegionModel(name: 'United States of America', code: 'US'),
  RegionModel(name: 'Uruguay', code: 'UY'),
  RegionModel(name: 'Uzbekistan', code: 'UZ'),
  RegionModel(name: 'Vanuatu', code: 'VU'),
  RegionModel(name: 'Venezuela (Bolivarian Republic of)', code: 'VE'),
  RegionModel(name: 'Viet Nam', code: 'VN'),
  RegionModel(name: 'Yemen', code: 'YE'),
  RegionModel(name: 'Zambia', code: 'ZM'),
  RegionModel(name: 'Zimbabwe', code: 'ZW'),
];

