// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'invidious_channel_resp.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

InvidiousChannelResp _$InvidiousChannelRespFromJson(
        Map<String, dynamic> json) =>
    InvidiousChannelResp(
      author: json['author'] as String?,
      authorId: json['authorId'] as String?,
      authorUrl: json['authorUrl'] as String?,
      authorBanners: (json['authorBanners'] as List<dynamic>?)
          ?.map((e) => AuthorBanner.fromJson(e as Map<String, dynamic>))
          .toList(),
      authorThumbnails: (json['authorThumbnails'] as List<dynamic>?)
          ?.map((e) => AuthorThumbnail.fromJson(e as Map<String, dynamic>))
          .toList(),
      subCount: (json['subCount'] as num?)?.toInt(),
      totalViews: (json['totalViews'] as num?)?.toInt(),
      joined: (json['joined'] as num?)?.toInt(),
      autoGenerated: json['autoGenerated'] as bool?,
      isFamilyFriendly: json['isFamilyFriendly'] as bool?,
      description: json['description'] as String?,
      descriptionHtml: json['descriptionHtml'] as String?,
      allowedRegions: (json['allowedRegions'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      tabs: (json['tabs'] as List<dynamic>?)?.map((e) => e as String).toList(),
      tags: json['tags'] as List<dynamic>?,
      authorVerified: json['authorVerified'] as bool?,
      latestVideos: (json['latestVideos'] as List<dynamic>?)
          ?.map((e) => LatestVideo.fromJson(e as Map<String, dynamic>))
          .toList(),
      relatedChannels: json['relatedChannels'] as List<dynamic>?,
    );

Map<String, dynamic> _$InvidiousChannelRespToJson(
        InvidiousChannelResp instance) =>
    <String, dynamic>{
      'author': instance.author,
      'authorId': instance.authorId,
      'authorUrl': instance.authorUrl,
      'authorBanners': instance.authorBanners,
      'authorThumbnails': instance.authorThumbnails,
      'subCount': instance.subCount,
      'totalViews': instance.totalViews,
      'joined': instance.joined,
      'autoGenerated': instance.autoGenerated,
      'isFamilyFriendly': instance.isFamilyFriendly,
      'description': instance.description,
      'descriptionHtml': instance.descriptionHtml,
      'allowedRegions': instance.allowedRegions,
      'tabs': instance.tabs,
      'tags': instance.tags,
      'authorVerified': instance.authorVerified,
      'latestVideos': instance.latestVideos,
      'relatedChannels': instance.relatedChannels,
    };
