part of 'watch_bloc.dart';

@freezed
class WatchState with _$WatchState {
  const factory WatchState({
    required WatchResp watchResp,
    required ExplodeWatchResp explodeWatchResp,
    required CommentsResp comments,
    required CommentsResp commentReplies,
    String? oldId,
    required ApiStatus fetchWatchInfoStatus,
    required ApiStatus fetchExplodeWatchInfoStatus,
    required bool isTapComments,
    required ApiStatus fetchCommentsStatus,
    required ApiStatus fetchCommentRepliesStatus,
    required bool isDescriptionTapped,
    required ApiStatus fetchMoreCommentsStatus,
    required bool isMoreCommetsFetchCompleted,
    required ApiStatus fetchMoreCommentRepliesStatus,
    required bool isMoreReplyCommetsFetchCompleted,
    required ApiStatus fetchSubtitlesStatus,
    required List<Map<String, String>> subtitles,
    required bool isPipEnabled,
    required String title,
    String? liveStreamUrl,
    required ApiStatus fetchExplodeLiveStreamStatus,
    List<MyRelatedVideo>? relatedVideos,
    required ApiStatus fetchExplodedRelatedVideosStatus,
    List<MyMuxedStreamInfo>? muxedStreams,
    required ApiStatus fetchExplodeMuxedStreamsStatus,
    VideoBasicInfo? selectedVideoBasicDetails,
  }) = _Initial;

  factory WatchState.initialize() => WatchState(
        watchResp: WatchResp(),
        explodeWatchResp: ExplodeWatchResp.initial(),
        comments: CommentsResp(),
        commentReplies: CommentsResp(),
        oldId: null,
        fetchWatchInfoStatus: ApiStatus.initial,
        fetchExplodeWatchInfoStatus: ApiStatus.initial,
        isTapComments: false,
        fetchCommentsStatus: ApiStatus.initial,
        fetchCommentRepliesStatus: ApiStatus.initial,
        isDescriptionTapped: false,
        fetchMoreCommentsStatus: ApiStatus.initial,
        isMoreCommetsFetchCompleted: false,
        fetchMoreCommentRepliesStatus: ApiStatus.initial,
        isMoreReplyCommetsFetchCompleted: false,
        fetchSubtitlesStatus: ApiStatus.initial,
        subtitles: [],
        isPipEnabled: false,
        title: '',
        liveStreamUrl: null,
        fetchExplodeLiveStreamStatus: ApiStatus.initial,
        relatedVideos: null,
        fetchExplodedRelatedVideosStatus: ApiStatus.initial,
        muxedStreams: null,
        fetchExplodeMuxedStreamsStatus: ApiStatus.initial,
        selectedVideoBasicDetails: null,
      );
}
