name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Kita pake channel stable terbaru biar aman
          channel: 'stable'
          cache: true # Biar lebih cepet

      - name: Get Dependencies
        # Kita paksa robotnya buat benerin masalah library dulu
        run: |
          flutter pub get

      - name: Build APK
        # Tambahin flag --no-pub biar dia nggak download ulang pas build
        run: flutter build apk --release --no-tree-shake-icons --no-pub

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fluxtube-indonesia
          path: build/app/outputs/flutter-apk/app-release.apk
