name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build Targeted APK
        # Mantera khusus biar langsing & cuma buat arm64-v8a
        run: flutter build apk --debug --target-platform android-arm64 --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fluxtube-v8-only
          path: build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk
