name: Build and Sign APK

on:
  push:
    branches: [ main ] # Ganti jadi 'master' jika branch utama lo namanya master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        # Perintah ini memastikan folder 'app' ada, lalu membuat file key.jks dari secret lo
        run: |
          mkdir -p app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/key.jks

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # Perintah build sambil mengirimkan password dari Secrets ke sistem
        run: ./gradlew assembleRelease
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: FluxTube-Release
          path: app/build/outputs/apk/release/*.apk
